name: Commitlint
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install commitlint
        run: |
          npm install -g conventional-changelog-conventionalcommits
          npm install -g commitlint@latest

      - name: Validate PR title with commitlint
        if: github.event_name == 'pull_request'
        run: echo '${{ github.event.pull_request.title }}' | commitlint --verbose